apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootazkv
spec:
  replicas: 3
  selector:
    matchLabels:
      service: springbootazkv
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        service: springbootazkv
    spec:
      containers:
        - name: springbootazkv
          image: jrobinson/spingbootazkvapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: azure_keyvault_client-key
              valueFrom:
                secretKeyRef:
                  name: dev-kv-secret
                  key: azure_keyvault_client-key
          envFrom:
            - configMapRef:
                name: dev-special-config